[package]
name = "hello-world"
version = "0.1.0"
authors = ["Ramiro Berrelleza <rberrelleza@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
pretty_env_logger = ""
tokio = { version = "0.2", features = ["full"] }

